name: spisetavle_flutter
description: SpiseTavle Flutter
publish_to: "none"

version: 1.0.0+11

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # Database
  sqflite: ^2.4.2
  path: ^1.9.1

  mobile_scanner: ^7.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/frida_data.db
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/tavle.png"
  remove_alpha_ios: true
